##On join welcome section
welcome-message: '&aWelcome %p to the server!'
welcome-title: ""
welcome-subtitle: ""
global-welcome-message: '&aWelcome to %p to this server!'
global-welcome: true
disable-welcome: false

##On join spawn section
spawn-every-join: true

##Spawn general section

#Number of blocks protected by PathFinder-Protection module
#If you not have PathFinder-Protection this options not work
spawn-protection: false
spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  world: ""

#Tpa section
tpa:
  #Max time for accept request
  max-time: 120
  #Only safe location
  only-safe-location: true


#Warp section
warp:
  #Damage protection time
  damage-safe-time: 120
  #Warp to only safe location
  only-safe-location: true
  #Warp cooldown command
  cooldown: 12
warps: {}

#Gamemode section
gamemode:
  #Only op gamemode
  only-op: false
  #Allows you to receive damage in creative
  creative-damage-allow: false

#Sign section
sign:
  #Allows you to color a sign
  colored-sign: true
  warp: true

#Staff chat section
staff-chat:
  #Staffchat format
  format: "&aSTAFF-CHAT &7> &f%p: &b%text"

#Freeze section
freeze:
  start-message: "&aCheat control!"
  move-message: "&aWarning: Cheat control in progress!"
  checker-format: "&a[CHECKER] &e%c: &b%text"
  controlled-format: "&c[CONTROLLED] &e%p: &b%text"
  finish: "&aCheat control is finish!"
  ignored-commands:
    - warp
    - spawn
    - tpa
  reasons:
    killaura:
      commands:
        - kick %p Killaura detected!
    exploit:
      commands:
        - kick %p Exploiting detected!
    nothing:
      commands:
        - spawn %p
        - spawn %c

#Afk section
afk:
  invulnerable: true

#Op list protection
op-list: {}

#Rules section
rules: "&a(1)This is a test%n&a(2)This is another test"

#Mention section
tag:
  mention-message: "&aYou have been mentioned by &e%p"
  mention-sound: "BLOCK_CHEST_OPEN"
  format: "&a%p: %text&e%tag"


#Randomtp section
random-tp:
  max-range: 500
  #Max attempts to search a safe location
  max-attempts: 5
  cooldown: 12


#Nickname section
nickname:
  #Allows you to select a colored nickname
  colors: false
  #Max lenght of custom nickname
  lenght: 12

economy:
  start-balance: 100.0
  use-economy: true


#Max lines of sign
warp-sign-format:
  - "&a[Warp]"
  - "&e%warpname%"
